# If the item cannot break the block, do we destroy it anyway or do we prevent is's destruction ?
do-break-block: true # set to "true" if the block can be broken but nothing will drop or to "false" if we prevent the player from breaking it

# Do we want to drop the XP after destroying a block ? 
# if do-break-block is "false" this won't affect anything
do-drop-xp: false # set to  "true" if you still want the XP to drop when a player destroy a block

# A list of block with the different items that can break it
blocks:
    dirt: # The dirt block can only broken by a Wooden Shovel, a Diamond Shovel or a Wither Rose
        - wooden_shovel
        - diamond_shovel
    redstone_ore:
        - netherite_pickaxe
    cobblestone: [] # The cobblestone cannot be broken

# A list of items with the blocks they can break
# This does NOT prevent an item from breaking a block (e.g. "diamond_axe: []" will NOT prevent the diamond axe from breaking other blocks)
# This list is only there if you have an item that can break multiple blocks to avoid repetition
items:
    gold_axe:
        - chest
        - trapped_chest
    wither_rose:
        # This is why the dirt block can be broken by a wither rose
        -  dirt
        - ladder
